### ISSUE TITLE
如何将图片变成扫描框中的四角边？

### ISSUE THREAD

**Issue by LixinQian** [zhang28602/ZZYQRCode_BarCode#2]
如何由这张[图片](https://github.com/zhang28602/ZZYQRCode/blob/master/Demo/Images.xcassets/qrcode_border.imageset/qrcode_border%402x.png)变成这样：[扫描中的框框](https://github.com/zhang28602/ZZYQRCode/blob/master/Screenshots/scan.png)

**Comment by zeyu1993** [comment]
// 加载图片
    UIImage *image = [UIImage imageNamed:@"qrcode_border"];
    
    // 设置端盖的值
    CGFloat top = image.size.height * 0.5;
    CGFloat left = image.size.width * 0.5;
    CGFloat bottom = image.size.height * 0.5;
    CGFloat right = image.size.width * 0.5;
    
    // 设置端盖的值
    UIEdgeInsets edgeInsets = UIEdgeInsetsMake(top, left, bottom, right);
    // 设置拉伸的模式
    UIImageResizingMode mode = UIImageResizingModeStretch;
    
    // 拉伸图片
    UIImage *newImage = [image resizableImageWithCapInsets:edgeInsets resizingMode:mode];

**Comment by LixinQian** [comment]
我在你的源码中没看见类似的操作，是不是在storyboard里设置了？

**Comment by zeyu1993** [comment]
你可以在工程中的Images.xcassets，选中你想要进行拉伸的图片后，在底部会出现一个Show Slicing的选项进行图片的拉伸操作
![default](https://user-images.githubusercontent.com/11890165/35310144-ef9ea8a8-00ea-11e8-923f-a974a3a749c6.png)
